### ISSUE TITLE
FR: launchpad capacity 

### ISSUE THREAD

**Issue by baczoni** [DavidEdwards/EVE-PI#14] opened 2017-01-28 21:07 UTC
It would be really nice if I could see how many p1 and p2 products are ready in my launchpads or storage facilities. Would love to see the volume as well in case I run out of storage space and would need to go and collect the stuff.

**Comment by DavidEdwards** [comment] 2017-01-29 09:57
Yeah, that is something I want to have built as well. However, at the moment it is restricted by ESI API.

I'll close this one since it is a duplicate of #7 (and possibly #3).

This is definitely something I want in the App.

**Closed by DavidEdwards** 2017-01-29 09:57 UTC
