### ISSUE TITLE
Decommissioned extractors not updated

### ISSUE THREAD

**Issue by HTL2001** [DavidEdwards/EVE-PI#26] opened 2017-04-03 05:59 UTC
When I decommission an extractor I have to clear the cache or it stays in alerts.

**Comment by DavidEdwards** [comment] 2017-04-03 11:20
This issue is currently by design.

I was previously deleting extractors with each resync with the EVE Servers. However, if the server has a hiccup and one planet doesn't refresh completely, this will leave you missing some extractors and being very confused!

I decided to not delete extractors with each resync. This means old extractors stay in the database. I added some easy to use cache clearing methods in the settings to fix this problem. Adding more power to the user.

At the moment I will not be fixing this. Howver, in the future I will make the resync method smarter.

**Comment by DefectiveNu** [comment] 2017-05-20 14:41
Your post on reddit reminded me I had this open still

Right now, the decomissioned extractors stick around for quite some time (I think at least a day?) so I'm using the cache clear every time I need an accurate picture of my planets.  If they could at least have some indication that they are "ghost" entries that'd be nice

**Comment by HTL2001** [comment] 2017-05-20 14:41
Your post on reddit reminded me I had this open still

Right now, the decomissioned extractors stick around for quite some time (I think at least a day?) so I'm using the cache clear every time I need an accurate picture of my planets. If they could at least have some indication that they are "ghost" entries that'd be nice

**Comment by DavidEdwards** [comment] 2017-05-20 15:12
Decommissioned extractors will stick around indefinitely until the cache is manually cleared.

I'll make this issue a priority.

**Comment by HTL2001** [comment] 2017-06-02 01:14
So it appears some cleared automatically, but, now one of them is stuck and I can't get to cache control to clear it (app crashes).  App in general seems a bit more prone to hanging now.

**Comment by DavidEdwards** [comment] 2017-06-19 11:50
I am struggling to reproduce this error. I keep testing this every few days to see if there is a change.

Do you still have this problem?

**Comment by HTL2001** [comment] 2017-06-20 03:23
The crash? doesn't seem to happen anymore, though, I can still get the app to hang a bit.  The extractors do seem to be clearing though.

Since the hangs/crashes came on the release you added error checking (I think), let me explain my typical setups:
Single planet P2 (2 variants):
2x extractors, 6x P1 factories, 3x P2 factories, 1 launchpad, outputs from every item routed to launchpad.
  These never had issues with cache.  These tend to produce "bad route" errors though, when there are no bad routes.
1x extractor, 2x storage, rest same as above: extractor is routed to one of the storages, and when its done, decommed/other P0 is set up and routed to other storage.  These would produce stale entries but no bad route errors
P1 colony: no problems, except if I move the extractor (same as above)

e: to add, I have 8 characters with 5 colonies a piece.  I'm thinking the hangs might be related to the error checking across that many colonies?

**Comment by DavidEdwards** [comment] 2017-06-20 11:42
I am pretty certain the hang ups are related to refreshing the character list.

Since that change, the character list shows the number of expired extractors and orders the character list by has-expired-extractors and alphabetically.

This is done each time the App loads or extractors are polled. This will be made more streamlined.

I will close this issue as I believe it to be resolved. Please let me know whether the new version fixes it for you. The new version will be released either today or tomorrow.

**Closed as completed by DavidEdwards** 2017-06-20 11:42 UTC
Labels: bug
