### ISSUE TITLE
Wrong number of factories

### ISSUE THREAD

**Issue by Xo6oToK** [DavidEdwards/EVE-PI#66] opened 2020-01-13 09:22 UTC
Double factories on screen. I have 6 at each planet, but see 12.

**Comment by DavidEdwards** [comment] 2020-01-13 12:21
Duplicate of #54. This particular system is not production ready.

**Closed as completed by DavidEdwards** 2020-01-13 12:21 UTC

**Comment by Xo6oToK** [comment] 2020-01-13 19:16
Ok, I'm sorry. I'm noob and say first what i see. I don't check previous
reports. My bad.

пн, 13 янв. 2020 г., 15:21 David Edwards <notifications@github.com>:
